export const ADD_PLACE = 'ADD_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'
export const REMOVE_PLACE = 'REMOVE_PLACE'
export const TRY_AUTH = 'TRY_AUTH'
export const UI_START_LOADING = 'UI_START_LOADING'
export const UI_STOP_LOADING = 'UI_STOP_LOADING'
export const SET_PLACES = 'SET_PLACES'
export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
